name: Grant Search Automation

on:
  push:
    branches:
      - main
      - development
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  search_grants:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Grant Searcher
        run: python main.py

      - name: Commit and push changes
        env:
          MY_USER_NAME: ${{ secrets.MY_USER_NAME }}
          MY_USER_EMAIL: ${{ secrets.MY_USER_EMAIL }}
        run: |
          git config --global user.name "$MY_USER_NAME"
          git config --global user.email "$MY_USER_EMAIL"
          git add grants.html
          git commit -m "Update grants.html" || echo "No changes to commit"
          git push || echo "No changes to push"
